name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Ensure html-webpack-plugin is installed
      run: npm install --save-dev html-webpack-plugin@2.28.0
      
    - name: Build project
      run: npm run build --if-present

    - name: Deploy to Linux server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          sudo apt-get update
          cd /home/node-apps/MyCV/
          git fetch origin main
          git reset --hard origin/main
          npm ci
          npm run build
          cp -R build/* /var/www/MyCV/build/
